### ISSUE TITLE
中文输入法在vim便利切换的问题

### ISSUE THREAD

**Issue by hongweiyi** [oldratlee/vim-practice#1]
说说我的，

Mac 下百度输入法：设置 -> 高级 -> 安静模式，设置程序列表。

可以把编码相关的程序都加进去，这样初始化均为英文输入

这样倒是可以解决大多数场景下的问题。至于要做到中文模式下在 Normal/Command 模式下自动切换英文模式，还没有好的解决方案。 : )

**Comment by oldratlee** [comment]
:+1: 多谢，我试试

**Comment by oldratlee** [comment]
Hi @hongweiyi 

@CodeFalling 已经给了完整的解法，详见[完美解决 Mac 下 Vim/Emacs 的输入法切换问题](https://www.jianshu.com/p/4d81b7e32bff) （[原文地址](https://codefalling.com/2015/11/02/fcitx-vim-for-OS-X/) 坏了）
1. 安装配合工具[fcitx-remote-for-osx](https://github.com/CodeFalling/fcitx-remote-for-osx)
2. 安装`Vim`插件[fcitx-vim-osx](https://github.com/CodeFalling/fcitx-vim-osx)

已经用起来了。 Works like a charm!

**Comment by hongweiyi** [comment]
赞啊，我看看。多谢

**Comment by zzptafc** [comment]
→ Bellkna:autocmd InsertEnter * set noimdisable
→ Bellkna:autocmd InsertLeave * set imdisable
from ppt 

非 vim 用戶 win 上測試幾次目測有效

**Comment by perkfly** [comment]
@oldratlee 链接挂了

**Comment by oldratlee** [comment]
> @oldratlee 链接挂了

已经更新
