### ISSUE TITLE
能把ycm插件也添加进去

### ISSUE THREAD

**Issue by tianser** [oldratlee/vim-practice#5]
建议把ycm的安装，使用并入文档；不知意向如何

**Comment by oldratlee** [comment]
收到，好！ `YCM`大神器！

**Comment by tianser** [comment]
@oldratlee 有需要文档，我可以提供哈

**Comment by oldratlee** [comment]
@cp542524698 太好了！ 👍 

方便的话，给个 `Pull Request`，新写一页，可以写些

- 常见问题
- 配置方式
- 关键好用的使用方式
- 相关资料

就像这样 https://github.com/oldratlee/vim-practice/tree/master/font-config

**Comment by tianser** [comment]
@oldratlee 周末整理一下

**Comment by oldratlee** [comment]
#7 已经给了pr
